config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  resources :pages
  resources :articles

  get 'signup', to: 'users#new'
  post 'pages/alpha',to:'pages#alpha'
  get 'pages/about', to: 'pages#about'
  get 'pages/aboutblog', to: 'pages#aboutblog'
  get 'tutorial', to: 'pages#tutorial'
  # get 'pages/alpha',to:'pages#alpha'
  # # post 'abc', to: 'pages#abc'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout' , to: 'sessions#destroy'

  
end

app/models/user.rb
class User < ApplicationRecord
  
    has_many :articles
    # has_many :comments
  
    before_save {self.email = email.downcase}
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true, length: { maximum: 105 },uniqueness: { case_sensitive: false },format: { with: VALID_EMAIL_REGEX }
  

  has_secure_password 

  VALID_PRN_REGEX = /\A(?=.*[a-z])[a-z\d]+\Z/i

  # validates :prn_number, presence: true , length: {maximum: 15}, uniqueness: { case_sensitive: true } , format: {with: VALID_PRN_REGEX }
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_same_user, only: [:edit,:update]
    # GET /users
    # GET /users.json
    def index
      @users = User.paginate(:page=>params[:page],per_page:2)
    end

    # GET /users/1
    # GET /users/1.json
    def show
       @user = User.find(params[:id])
       @articles = @user.articles.paginate(:page=>params[:page],per_page:2)
    end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to login_path }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.require(:user).permit(:username, :email, :password, :admin, :firstname, :lastname, :prn_number ,:DOB, :Course, :Gender, :Bio)
      end

      def require_same_user
        if current_user != @user
          flash[:danger]="You can edit only your content"
          redirect_to root_path
        end
      end

  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true,:html => {class: "form-horizontal", role: "form"}) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h3>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li style="color: red;"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
      <div class="control-label col-sm-2">
          <%= form.label :username, "Username" %>
      </div>

      <div class="col-sm-8">
        <%= form.text_field :username, class: "form-control", placeholder: "Username", autofocus: true, required: true %>
      </div>
  </div>

   <div class="form-group">
      <div class="control-label col-sm-2">
          <%= form.label :firstname, "FirstName" %>
      </div>

      <div class="col-sm-8">
        <%= form.text_field :firstname, class: "form-control", placeholder: "Firstname", autofocus: true, required: true %>
      </div>
  </div>

  <div class="form-group">
      <div class="control-label col-sm-2">
          <%= form.label :lastname, "Lastname" %>
      </div>

      <div class="col-sm-8">
        <%= form.text_field :lastname, class: "form-control", placeholder: "Lastname", autofocus: true , required: true%>
      </div>
  </div>
  <% if !logged_in? %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label :prn_number, "PRN Number" %>
        </div>

        <div class="col-sm-8">
          <%= form.text_field :prn_number, class: "form-control", placeholder: "PRN number", autofocus: true, required: true %>
        </div>
    </div>
  <% else %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label :prn_number, "Teacher ID" %>
        </div>

        <div class="col-sm-8">
          <%= form.text_field :prn_number, class: "form-control", placeholder: "Teacher ID", autofocus: true , required: true%>
        </div>
    </div>
  <% end %>  
  <div class="form-group">
      <div class="control-label col-sm-2">
          <%= form.label :email, "Email" %>
      </div>

      <div class="col-sm-8">
        <%= form.email_field :email, class: "form-control", placeholder: "Email", autofocus: true , required: true%>
      </div>
  </div>
  <div class="form-group">
      <div class="control-label col-sm-2">
          <%= form.label :password, "Password" %>
      </div>

      <div class="col-sm-8">
        <%= form.password_field :password, class: "form-control", placeholder: "password", autofocus: true ,required: true%>
      </div>
  </div>
  <%if !logged_in? %>
    <div class="form-group">
      <div class="control-label col-sm-2">
          <%= form.label :Course, "Course" %>
      </div>

      <div class="col-sm-8">
        <%= form.text_field :Course, class: "form-control", placeholder: "Course", autofocus: true ,required: true%>
      </div>
    </div>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label :Gender, "Gender" %>
        </div>

        <div class="col-sm-3">
          <%= radio_button_tag(:Gender, "male", checked = true) %><strong>  Male</strong>
        </div>
        <div class="col-sm-3">  
          <%= radio_button_tag(:Gender, "female", checked = false) %>
          <strong>  Female</strong>
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label :DOB, "Date Of Birth" %>
        </div>

        <div class="col-sm-8">
          <%= form.text_field :DOB, class: "form-control", "data-provide" => 'datepicker', autofocus: true ,required: true%>
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= form.label :Bio, "About Yourself" %>
        </div>

        <div class="col-sm-8">
          <%= form.text_area :Bio, class: "form-control", placeholder: "About Yourself", autofocus: true%>
        </div>
    </div>
  <%end%>
  <% if logged_in? %>
     <%if current_user.admin? %>
      <div class="form-group">
          <div class="control-label col-sm-2">
              <%= form.label :admin, "Admin" %>
          </div>

          <div class="col-sm-8">
            <%= form.check_box :admin, :value => false %>
          </div>
      </div>
    <% end %>
  <% end %>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-2">
      <%= form.submit "Submit", class: "btn btn-primary btn-lg"%>
    </div>  
</div>
<!-- </div> -->
<% end %>     

app/views/users/edit.html.erb
<head>
   <style>
        body {
            background: url(<%= asset_path '8BWvUj.jpg' %>);
            background-size: cover;
            background-attachment: fixed;

            }
    </style> 

</head>

<body>
<div class="articleform">
<center style="margin-top: 5%"><h1 style="color: rgb(0,0,128);">Edit Profile </h1></center>

	<%= render 'form', user: @user %>

	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path%>
</div>	
</body>

app/views/users/index.html.erb
<head>
   <style>
        body {
            background: url(<%= asset_path '8BWvUj.jpg' %>);
            background-size: cover;
            background-attachment: fixed;
            }
    </style> 

</head>
<body>  
<div id="page-content">
  <p id="notice"><%= notice %></p>
  <h2 class="text-center mt-3" style="color:#fff; text-decoration-style: solid;">Users</h2>
  <div class="container">
    <% @users.each do |user|%>
        <div class="col-8 mt-4" style="margin-left: 370px;">
          <div class="panel panel-info shadow mb-5 bg-white rounded" style="width: 50%;">
            <div class="panel-heading font-italic">
              <nav class="nav">
                  <ul class="nav navbar-nav">
                    <li ><%= link_to 'Show', user %></li>
                    <% if current_user.admin?%>
                    <li><%= link_to 'Edit', edit_user_path(user) %></li>
                    <li><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }%></td></li>
                    <%end%>
                  </ul>
              </nav>
            </div>
            <div class="panel-body">
              <label>Name: <%=user.username%></label>
              <label>Email: <%=user.email%></label>
              <label>Firstname: <%=user.firstname%></label>
              <label>Lastname: <%=user.lastname%></label>
              <label>PRN Number: <%=user.prn_number%></label>
              <label>DOB: <%=user.DOB%></label>
              <label>Gender: <%=user.Gender%></label>
              <label>Course: <%=user.Course%></label>
              <label>Bio: <%=user.Bio%></label>

              <%if user.admin?%>
                <label>Role: Teacher</label>
              <%else%>
                <label>Role: Student</label>
              <%end%>  
            </div>
          </div>
        </div>
    <% end %>
  </div>
  <center><%= will_paginate @users, renderer: BootstrapPagination::Rails %></center>
  <center>  <%= link_to 'New Student',new_user_path, class:'btn btn-info' %>
  </center>
</div>
</body>>
<!-- ============================================================================ -->
  <!-- Buttons to choose list or grid view -->
  

app/views/users/new.html.erb
<!-- <center style="margin-top: 5%"><h1 style="color: rgb(0,0,128);">SignUp Form </h1></center> -->
<head>
    <style>
        body {
            background: url(<%= asset_path '8BWvUj.jpg' %>);
            background-size: cover;
            background-attachment: fixed;
            }
    </style>        
</head>
<body>
<div class="left">
    <h1><%= image_tag("logo2.png", size: "200x200", alt: "Edit Entry")%></h1>
    <p>A platform where you can share your thoughts</p>
 </div>

<div class="sign">
    <%if !logged_in?%>
	<h3 align="center" style="margin-bottom: 5px;">Sign Up</h3>
    <%else%>
    <h3 align="center" style="margin-bottom: 5px;">Create Admin</h3>
    <%end%>
	<%= render 'form', user: @user %>
    <%if !logged_in?%>
	<span>Do you already have an account? </span><%= link_to 'Log In', login_path %>
    <%end%>
</div>


<br><br><br>
</body>
<!-- <div class="footer">
<%= link_to 'Back', pages_path %>
</div> -->

app/views/users/show.html.erb
<style>
    body {
        background: url(<%= asset_path '8BWvUj.jpg' %>);
        background-size: cover;
        background-attachment: fixed;
        }

    img { 
      width: 115px; 
      height: 115px; 
    }

    * {
      box-sizing: border-box;
    }

    body {
      font-family: Arial, Helvetica, sans-serif;
    }

    /* Float four columns side by side */
    .column {
      float: left;
      width: 10%;
      padding: 0 1px;
    }

   
    /* Remove extra left and right margins, due to padding */
    .row {margin: 0 -5px;}

    /* Clear floats after the columns */
    .row:after {
      content: "";
      display: table;
      clear: both;
    }

    /* Responsive columns */
    @media screen and (max-width: 900px) {
      .column {
        width: 100%;
        display: block;
        margin-bottom: 20px;
      }
      size{
        height: 200px;
      }
    }

    /* Style the counter cards */
    .card {
      background-color: rgba(245, 245, 245, 0.8);
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      padding: 16px;
    }
</style>




<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
  width: 40%;
}

.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

.container {
  padding: 2px 16px;
}
</style>
</head>
<body>

<center>
<div class="card" style="text-align: left">
  <center>
    <h4><b>My Profile</b></h4>
    <hr>
    <%= gravatar_for @user, size: 500%>
    <h4><b>Total Posts:<%=  @articles.count %> </b> </h4>    
  </center>

  <div class="container">
    <div class="row">
      <div class="column">
        <label><strong> User Name:</strong></label>
        <label><strong> First Name:</strong></label>
        <label><strong> PRN Number:</strong></label>
        <%if @user.admin?%>
        <strong> <label>Role:</label></strong>
        <%else%>
          <strong> <label>Role:</label></strong>
        <%end%>
        <label><strong> DOB:</strong></label>
        <label><strong> Gender:</strong></label>
        <label><strong> Course:</strong></label>
        <label><strong> About My Self:</strong></label>
      
      </div>
      <div class="column">
        <label><%=@user.username%></label>
        <label><%=@user.firstname%></label>
        <label><%=@user.prn_number%></label>
        <%if @user.admin?%>
          <label>Teacher</label>
        <%else%>
          <label>Student</label>
        <%end%>
        <label><%=@user.DOB%></label>
        <label><%=@user.Gender%></label>
        <label><%=@user.Course%></label>
        

        
            
     </div>
    </div>
    <div style="width: 35%">
     <i> <%=@user.Bio%> </i>
    </div>
  </div>
  <center>
    <%if logged_in?%>
    <%if current_user == @user || current_user.admin?%>
    <%= link_to "Edit Profile", edit_user_path(@user), class: 'btn btn-xs btn-default'%>
    <%end%>
    <%end%>
  </center>
</div>
</center>

</body>
</html> 