config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  resources :pages
  resources :articles

  get 'signup', to: 'users#new'
  post 'pages/alpha',to:'pages#alpha'
  get 'pages/about', to: 'pages#about'
  get 'pages/aboutblog', to: 'pages#aboutblog'
  get 'tutorial', to: 'pages#tutorial'
  # get 'pages/alpha',to:'pages#alpha'
  # # post 'abc', to: 'pages#abc'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout' , to: 'sessions#destroy'

  
end

app/views/layouts/_footer.html.erb
<div class="container">

<footer class="footer">

<small>

Copyright © <a href="https://www.google.com">My Blog : StudentsCorner</a>

by Sachin Ujjainkar,Megha Sonkusare and Harshada Chinchole

</small>

<nav>

<ul>
</ul>

</nav>

</footer>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <li><%= link_to 'StudentsCorner', root_path, class: "navbar-brand", id:"logo"%></li>
        
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'User', users_path%></li>
        
          <li><%= link_to 'New Article', new_article_path %></li>
        <%end%>
      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
          <li><%=link_to 'Log out', logout_path , method: :delete%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            My Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if logged_in? && current_user.admin? %>
                <li><%= link_to 'Create Admin', new_user_path %></li>
              <%end%>
              <li><%=link_to 'Edit my profile', edit_user_path(current_user)%></li>
              <li><%=link_to 'View my profile', user_path(current_user)%></li>
            </ul>
          </li>
          <li> <%=link_to 'Video',  tutorial_path %></li>
      <% else %>
          <li><%=link_to 'Login', login_path%></li>
          <li><%=link_to 'Signup', signup_path%></li>
      <% end %>
      <li> <%=link_to 'About',  pages_aboutblog_path %></li>
      </ul>

      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentCorner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%=render 'layouts/navigation'%>  
  <%=render 'articles/message'%>

 <div class="container">
    <%= yield %>
  </div> 
  <%= render 'layouts/footer'%>
  </body>
</html>